Add accounts method to global state api
spacemeshos/api pull request #121
Opened 2020-11-01 13:27 UTC by avive

Required so we can add this capability to the api.

2020-11-02 13:12 UTC, lrettig requested changes
See question

2020-11-02 13:14 UTC, avive commented on proto/spacemesh/v1/global_state_types.proto
> +    repeated Account account_wrapper = 1;
We can add a streaming method as well but I think that the pull one should be fine for now and solve the short term issue we have with testnet accounts and the issue with accounts in go-sm logs.

2020-11-02 16:43 UTC, avive commented
Moved to DebuggingService.

2020-11-03 00:09 UTC, lrettig approved these changes
I gave the service a shorter name and added a note about not using the new service in production. LGTM.

2020-11-03 00:12 UTC, merged