adds publicKey grpc endpoint
spacemeshos/api pull request #147
Opened 2021-05-28 18:31 UTC by benbot

I was looking for this myself when I came across #141.

If this looks good to everyone I could add it to go-spacemesh as well.

I was running into a weird issue when running `make build`.

It can't find the definition for `HttpRule`

2021-06-11 22:18 UTC, lrettig commented
I'm okay with this. @narayanprusty @AmitShaul does it look good to you guys?

2021-06-14 08:11 UTC, narayanprusty approved these changes

2021-06-14 08:14 UTC, avive commented
q: is the public key returned here different or same to smesher id in atxs?

2021-07-28 17:41 UTC, lrettig requested changes

2021-07-28 17:41 UTC, lrettig commented on proto/spacemesh/v1/debug.proto
> +    // PublicKey returns this node's public key
Could you expand this comment to explain exactly which public key is returned? go-spacemesh actually uses several public keys. See https://github.com/spacemeshos/go-spacemesh/issues/2269 for more.

2022-12-22 16:30 UTC, closed without merging